name: Build

on:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main
      - release/v1

jobs:

  build:

    name: Build

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Publish
      run: dotnet publish src/PSStreamLogger.sln -c Release -f netstandard2.0 -o "publish"

    - name: Create artifact directory
      run: New-Item -ItemType Directory -Path "../artifact/psstreamlogger" -Force
      shell: pwsh

    - name: Copy files to artifact directory
      run: Copy-Item -Path "publish/*" -Destination "../artifact/psstreamlogger" -Include @("*.dll", "*.psd1")
      shell: pwsh

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: PSStreamLogger
        path: ../artifact/psstreamlogger
