name: Build

on:

  push:
    branches:
      - main
      - romandres-v1-fullcrl

jobs:

  build_coreclr:
    name: Build CoreCLR
    uses: romandres/PStreamLogger/.github/workflows/templates/build.yml@romandres-v1-fullcrl
    with:
      targetFramework: netstandard2.0

  build_fullclr:
    name: Build FullCLR
    uses: romandres/PStreamLogger/.github/workflows/templates/build.yml@romandres-v1-fullcrl
    with:
      targetFramework: net48

  # publish:
  #   if: ${{ !startswith(github.ref, 'refs/pull/') }}

  #   name: Publish
  #   environment: psgallery
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:

  #   - name: Download artifact
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: PSStreamLogger
  #       path: ./PSStreamLogger

  #   - name: Publish module to PSGallery
  #     run:  Publish-Module -Path .\PSStreamLogger -NuGetApiKey "${{ secrets.PSGALLERY_API_KEY }}" -Verbose
  #     shell: pwsh
