name: CI build

on:

  push:
    branches:
      - main
      - romandres-v1-fullcrl

jobs:

  build_coreclr:
    name: CoreCLR
    uses: ./.github/workflows/reusable_build.yml
    with:
      targetFramework: netstandard2.0
      runsOn: ubuntu-latest
      artifactName: PSStreamLogger-CoreCLR

  build_fullclr:
    name: FullCLR
    uses: ./.github/workflows/reusable_build.yml
    with:
      targetFramework: net48
      runsOn: windows-latest
      artifactName: PSStreamLogger-FullCLR

  publish:
    uses: ./.github/workflows/reusable_publish_release.yml
    needs: build_coreclr
    with:
      commit: ${{ github.sha }}
      tag: ${{ needs.build_coreclr.outputs.releaseVersion }}
      isPrerelease: ${{ needs.build_coreclr.outputs.isPrerelease }}
