name: Build

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build
      run: dotnet build src/PSStreamLogger.sln --configuration Release
    - name: Create artifact directory
      run: New-Item -ItemType Directory -Path "../artifact/psstreamlogger-psmodule" -Force
      shell: pwsh
    - name: Copy files to artifact directory
      run: Copy-Item -Path "src/PSStreamLogger/bin/Release/netstandard2.0/*" -Destination "../artifact/psstreamlogger-psmodule" -Include @("*.dll", "*.psd1")
      shell: pwsh
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: PSStreamLogger-PSModule
        path: ../artifact/psstreamlogger-psmodule
