name: CI build

on:

  pull_request:

jobs:

  build_coreclr:
    name: CoreCLR
    uses: ./.github/workflows/reusable_build.yml
    with:
      targetFramework: netstandard2.0
      runsOn: ubuntu-latest
      artifactName: PSStreamLogger-CoreCLR

  build_fullclr:
    name: FullCLR
    uses: ./.github/workflows/reusable_build.yml
    with:
      targetFramework: net48
      runsOn: windows-latest
      artifactName: PSStreamLogger-FullCLR
