name: CI build

on:
  pull_request:

jobs:

  build_coreclr:
    name: Build CoreCLR
    uses: romandres/PStreamLogger/.github/workflows/templates/build.yml@romandres-v1-fullcrl
    with:
      targetFramework: netstandard2.0

  build_fullclr:
    name: Build FullCLR
    uses: romandres/PStreamLogger/.github/workflows/templates/build.yml@romandres-v1-fullcrl
    with:
      targetFramework: net48
