name: Publish Module

on:

  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      PSGALLERY_API_KEY:
        required: true

jobs:

  publish:
    name: Publish Module
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest

    steps:

    - uses: robinraju/release-downloader@v1.5
      with:
        tag: ${{ inputs.tag }}
        fileName: "PSStreamLogger.zip"
        out-file-path: "download"

    - name: Expand archive
      run:  Expand-Archive -Path ./download/PSStreamLogger.zip -DestinationPath "./PSStreamLogger"
      shell: pwsh

    - name: Publish module to PSGallery
      run:  Publish-Module -Path .\PSStreamLogger -NuGetApiKey "${{ secrets.PSGALLERY_API_KEY }}" -Verbose -WhatIf
      shell: pwsh
